fullnameOverride: golang-hands-on

replicaCount: 1

ingress:
  enabled: true
  subdomain: 
  basedomain: 
  hosts: 
    - golang-hands-on.okc1.opsnow.com
  annotations:
    kubernetes.io/ingress.class: nginx
    # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    # ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  labels: {}

autoscaling:
  enabled: false
  min: 1
  max: 5
  cpu: 80
  mem: 80

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 220m
    memory: 512Mi

#readinessProbe:
#  httpGet:
#    path: /health
#    port: 3000
#  initialDelaySeconds: 10
#  periodSeconds: 5
#  failureThreshold: 60

#livenessProbe:
#  httpGet:
#    path: /health
#    port: 3000
#  initialDelaySeconds: 10
#  periodSeconds: 5
#  failureThreshold: 60

configmap:
  enabled: false

secret:
  enabled: true
